FROM phusion/baseimage:0.9.15
MAINTAINER smdion <me@seandion.com>

# Set correct environment variables
ENV HOME /root
ENV DEBIAN_FRONTEND noninteractive
ENV LC_ALL C.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8

# Use baseimage-docker's init system
CMD ["/sbin/my_init"]

# Configure user nobody to match unRAID's settings
 RUN \
 usermod -u 99 nobody && \
 usermod -g 100 nobody && \
 usermod -d /home nobody && \
 chown -R nobody:users /home

# Disable SSH
RUN rm -rf /etc/service/sshd /etc/my_init.d/00_regen_ssh_host_keys.sh

# Install PROGRAM
RUN \

#Add required Dependencies for FreeDNS
RUN cpanm --sudo Digest::SHA1

#Expose Volumes
VOLUME /config

#Expose Ports
EXPOSE 80

# Add firstrun.sh to execute during container startup
ADD firstrun.sh /etc/my_init.d/firstrun.sh
RUN chmod +x /etc/my_init.d/firstrun.sh

# Add PROGRAM to runit
RUN mkdir /etc/service/PROGRAM
ADD PROGRAM.sh /etc/service/PROGRAM/run
RUN chmod +x /etc/service/PROGRAM/run